# Generated by Django 4.2.23 on 2025-06-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktable', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['user'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='llergies',
            new_name='allergies',
        ),
    ]
